modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Sxilverr"
description = "Customizable player spawn conditions"
logoFile = "assets/${id}/icon.png"
logoBlur = false
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "spawnconditions-common.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"
